DROP TABLE IF EXISTS class_skill CASCADE;

CREATE TABLE class_skill (
  character                     INTEGER REFERENCES character(id) NOT NULL,
  class                         character_class_name NOT NULL,
  skill                         skill_name NOT NULL,
  rank_points                   SMALLINT,
  racial_points                 SMALLINT,
  feats_points                  SMALLINT,
  synergy_points                SMALLINT,
  misc_points                   SMALLINT,
  armor_check_penalty_points    SMALLINT,

  PRIMARY KEY(character, class, skill)
);
